# fly.toml app configuration file generated for spam-encoder-2 on 2026-07-04T09:46:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spam-encoder-2'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "8080"

[processes]
  app = "./bin/rake litestream:run ./bin/rails server"

[mounts]
  source = "data"
  destination = "/data"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "10GB"
